// EXAMPLE_TYPE
export const EXAMPLE_TYPE = "EXAMPLE_TYPE";

// AUTH TYPES
export const AUTH_LOGIN_USER = "AUTH_LOGIN_USER";
export const AUTH_LOGIN_USER_FAIL = "AUTH_LOGIN_USER_FAIL";
export const AUTH_LOGIN_USER_SUCCESS = "AUTH_LOGIN_USER_SUCCESS";
export const AUTH_CREATE_USER = "AUTH_CREATE_USER";
export const AUTH_CREATE_USER_FAIL = "AUTH_CREATE_USER_FAIL";
export const AUTH_CREATE_USER_SUCCESS = "AUTH_CREATE_USER_SUCCESS";
export const AUTH_LOGOUT_USER = "AUTH_LOGOUT_USER";
